import type { ClassIdentityProps } from "./internal/helper";
export {};

declare global {
    /** unfinished */
    const pb2AIModule: ClassIdentityProps<"pb2AIModule"> & {
        readonly ALL_TYPES: any;
        readonly BEHAVIOR_IDLE: any;
        readonly BEHAVIOR_INVESTIGATE: any;
        readonly BEHAVIOR_LOOK_AROUND: any;
        readonly BEHAVIOR_MPBOT: any;
        readonly BEST_ATTACK_BULLET: any;
        readonly BEST_ATTACK_ENTITY: any;
        readonly BEST_ATTACK_NOATOM: any;
        readonly BEST_ATTACK_SHAPE: any;
        readonly BULLET_COLLISION_LOGIC_EXPLODE: any;
        readonly BULLET_COLLISION_LOGIC_GRENADE: any;
        readonly BULLET_COLLISION_LOGIC_MIRROR: any;
        readonly BULLET_COLLISION_LOGIC_PENETRATE: any;
        readonly COEF_MULT_GLOBAL: any;
        readonly COMBAT_LEVEL_BOTH_ENEMIES_AND_TRACESHOTS: any;
        readonly COMBAT_LEVEL_NO_COMBAT: any;
        readonly COMBAT_LEVEL_ONLY_IF_ENEMY_IS_VISIBLE: any;
        CreateAI(...args: unknown[]): unknown;
        readonly FAIL_WAY_LINE_COST_PER_FAILURE: any;
        readonly FILTER_ANY: any;
        readonly FILTER_ANY_ANYWHERE: any;
        readonly FILTER_ANY_ANYWHERE_PING_RANGE: any;
        readonly FILTER_FLOOR: any;
        readonly FILTER_FLOOR_AND_WATER: any;
        readonly FILTER_WATER: any;
        readonly FIRE_COEF: any;
        readonly FIRST_WEAPON_SLOT: any;
        readonly GOTO_MODE_DELAY_PREVIOUSLY_SCHEDULED: any;
        readonly GOTO_MODE_EXECUTE_AFTER_PREVIOUSLY_SCHEDULED: any;
        readonly GOTO_MODE_OVERRIDE_PREVIOUSLY_SCHEDULED: any;
        readonly GUN_MODE_CURRENT: any;
        readonly HINT_ACTION_ATTACK_OBJECT: any;
        readonly HINT_ACTION_GO_TO: any;
        readonly HINT_ACTION_JUST_WAIT: any;
        readonly HINT_ACTION_SHOOT_AT_POINT: any;
        readonly HINT_ACTION_USE_SWITCH: any;
        readonly LASER_MINE_COEF: any;
        readonly MOVABLE_ON_A_LINE_COST_PER_HITPOINT: any;
        readonly MOVABLE_ON_A_LINE_COST_PER_MOVABLE: any;
        readonly NO_SLOT: any;
        readonly PROX_MINE_COEF: any;
        readonly REACH_TACTIC_CLEARING_PATH: any;
        readonly REACH_TACTIC_CROUCH: any;
        readonly REACH_TACTIC_FALL: any;
        readonly REACH_TACTIC_HINT: any;
        readonly REACH_TACTIC_JUMP: any;
        readonly REACH_TACTIC_NAMES: any;
        readonly REACH_TACTIC_PRICES: any;
        readonly REACH_TACTIC_SELFBOOST: any;
        readonly REACH_TACTIC_SELF_HEALING: any;
        readonly REACH_TACTIC_SWIM: any;
        readonly REACH_TACTIC_SWIM_JUMP: any;
        readonly REACH_TACTIC_SWIM_SELFBOOST: any;
        readonly REACH_TACTIC_SWORDJUMP: any;
        readonly REACH_TACTIC_THREAT_PRICES: any;
        readonly REACH_TACTIC_UNREACHABLE: any;
        readonly REACH_TACTIC_WALK: any;
        readonly REACH_TACTIC_WALLJUMP_END: any;
        readonly REACH_TACTIC_WALLJUMP_LOOP: any;
        readonly REACH_TACTIC_WALLJUMP_START: any;
        readonly REACH_TACTIC_WALLJUMP_START_SWORDS: any;
        readonly SEQUENCE_BEHAVIOR_MAD: any;
        readonly SEQUENCE_BEHAVIOR_SERIOUS: any;
        readonly SEQUENCE_BEHAVIOR_SILLY: any;
        readonly SHIELDED_COEF: any;
        readonly TASK_TYPE_BASIC_GOTO: any;
        readonly TASK_TYPE_OXYGEN_RUSH: any;
        readonly TASK_TYPE_TEAMMATE_FOLLOW: any;
        readonly TASK_TYPE_TEAMMATE_HEAL: any;
        readonly TASK_TYPE_THREAT_HUNT: any;
        readonly TIME_WARP_COEF: any;
        readonly TOXIC_GAS_COEF: any;
        readonly VISITED_HINT_LINE_COST: any;
        readonly WAYPOINT_TYPE_FLOOR: any;
        readonly WAYPOINT_TYPE_SLIDING_FLOOR: any;
        readonly WAYPOINT_TYPE_UNDEFINED: any;
        readonly WAYPOINT_TYPE_WALL: any;
        readonly WAYPOINT_TYPE_WATER: any;
    };
    
    /** unfinished */
    type pb2AIModuleInstance = ClassIdentityProps<"pb2AIModule"> & {
        readonly skill: unknown;
        readonly controller: unknown;
        readonly allow_trace_shots: unknown;
        readonly allow_hit_reporting: unknown;
        readonly bot_decided_hunt_threat: unknown;
        readonly bot_decided_teammate_heal: unknown;
        GoTo(...args: unknown[]): unknown;
    };
}