import type { ClassIdentityProps } from "./internal/helper";
export {};

declare global {
    /** unfinished auto-generated */
    const pb2GameWorld: ClassIdentityProps<"pb2GameWorld"> & {
        CancelPointOfViewReplay(...args: unknown[]): unknown;
        CreateBoxShape(...args: unknown[]): unknown;
        DownloadModules(...args: unknown[]): unknown;
        DownloadSounds(...args: unknown[]): unknown;
        DownloadTextures(...args: unknown[]): unknown;
        EnableSimplePlayerAssignmentLogic(...args: unknown[]): unknown;
        FinalizeNewMovables(...args: unknown[]): unknown;
        FinalizeWorld(...args: unknown[]): unknown;
        GetBounds(...args: unknown[]): unknown;
        GetPing(...args: unknown[]): unknown;
        IsHostSpectating(...args: unknown[]): unknown;
        IsWatchingReplay(...args: unknown[]): unknown;
        SetDisconnectActionDescriptionStructure(...args: unknown[]): unknown;
        SetReplayTimeScale(...args: unknown[]): unknown;
        SetToController(...args: unknown[]): unknown;
        SetToFreeCamera(...args: unknown[]): unknown;
        SetToSpectateRagdoll(...args: unknown[]): unknown;
        ShakeScreen(...args: unknown[]): unknown;
        ShowChatMessage(...args: unknown[]): unknown;
        StartPointOfViewReplay(...args: unknown[]): unknown;
        readonly background_snow: unknown;
        readonly background_terrain_random_seed: unknown;
        readonly connected: unknown;
        readonly controller: unknown;
        readonly default_lamp_color: unknown;
        readonly fog_intensity: unknown;
        readonly foliage_random_seed: unknown;
        readonly foliage_shadow_multiplier: unknown;
        readonly foreground_platform_random_seed: unknown;
        readonly foreground_snow: unknown;
        readonly foreground_terrain_random_seed: unknown;
        hud_custom_bars: unknown;
        readonly hud_show_character_info: unknown;
        readonly hud_visible: unknown;
        readonly isHost: unknown;
        readonly light_power_multiplier: unknown;
        readonly nickname_tagged: unknown;
        readonly personal_virtual_controller: unknown;
        readonly raining: unknown;
        readonly settings: unknown;
        readonly sky_color: unknown;
        readonly sky_intensity: unknown;
        readonly snowing: unknown;
        readonly spectated_ragdoll: unknown;
        readonly sun_color: unknown;
        readonly sun_intensity: unknown;
        readonly sun_shade_x: unknown;
        readonly sun_shade_y: unknown;
        readonly terrain_enabled: unknown;
        readonly terrain_extra_sky_ground_contrast: unknown;
        readonly terrain_extra_space_x: unknown;
        readonly terrain_extra_space_y: unknown;
        readonly terrain_force_low_level_terrain: unknown;
        readonly terrain_fractal_cube_size: unknown;
        readonly terrain_level_influence_factor: unknown;
        readonly terrain_phys_scale: unknown;
        readonly terrain_post_tesselation_grass_noise: unknown;
        readonly terrain_remove_floating_islands: unknown;
        readonly terrain_size_z: unknown;
        readonly terrain_sky_ground_contrast: unknown;
        readonly terrain_solve_random_factor: unknown;
        readonly terrain_start_z: unknown;
        readonly terrain_uv_relax_iterations: unknown;
        readonly terrain_y_offset: unknown;
        readonly user_uid: unknown;
        readonly wind_amplitude: unknown;
        readonly wind_random_part: unknown;
    };
}