import type { ClassIdentityProps } from "./internal/helper";
export {};

declare global {
    /** unfinished */
    const pb2GameWorld: ClassIdentityProps<"pb2GameWorld"> & {
        CancelPointOfViewReplay(...args: unknown[]): unknown;
        CreateBoxShape(...args: unknown[]): unknown;
        DownloadModules(...args: unknown[]): unknown;
        DownloadSounds(...args: unknown[]): unknown;
        DownloadTextures(...args: unknown[]): unknown;
        EnableSimplePlayerAssignmentLogic(...args: unknown[]): unknown;
        FinalizeNewMovables(...args: unknown[]): unknown;
        FinalizeWorld(...args: unknown[]): unknown;
        GetBounds(...args: unknown[]): unknown;
        GetPing(...args: unknown[]): unknown;
        IsHostSpectating(...args: unknown[]): unknown;
        IsWatchingReplay(...args: unknown[]): unknown;
        SetDisconnectActionDescriptionStructure(...args: unknown[]): unknown;
        SetReplayTimeScale(...args: unknown[]): unknown;
        SetToController(...args: unknown[]): unknown;
        SetToFreeCamera(...args: unknown[]): unknown;
        SetToSpectateRagdoll(...args: unknown[]): unknown;
        ShakeScreen(...args: unknown[]): unknown;
        ShowChatMessage(...args: unknown[]): unknown;
        StartPointOfViewReplay(...args: unknown[]): unknown;
        background_snow: unknown;
        background_terrain_random_seed: unknown;
        readonly connected: unknown;
        readonly controller: pb2ControllerInstance | null;
        default_lamp_color: unknown;
        fog_intensity: unknown;
        foliage_random_seed: unknown;
        foliage_shadow_multiplier: unknown;
        foreground_platform_random_seed: unknown;
        foreground_snow: unknown;
        foreground_terrain_random_seed: unknown;
        hud_custom_bars: unknown;
        hud_show_character_info: unknown;
        hud_visible: unknown;
        readonly isHost: unknown;
        light_power_multiplier: unknown;
        readonly nickname_tagged: unknown;
        readonly personal_virtual_controller: unknown;
        raining: unknown;
        readonly settings: unknown;
        sky_color: unknown;
        sky_intensity: unknown;
        snowing: unknown;
        readonly spectated_ragdoll: unknown;
        sun_color: unknown;
        sun_intensity: unknown;
        sun_shade_x: unknown;
        sun_shade_y: unknown;
        terrain_enabled: unknown;
        terrain_extra_sky_ground_contrast: unknown;
        terrain_extra_space_x: unknown;
        terrain_extra_space_y: unknown;
        terrain_force_low_level_terrain: unknown;
        terrain_fractal_cube_size: unknown;
        terrain_level_influence_factor: unknown;
        terrain_phys_scale: unknown;
        terrain_post_tesselation_grass_noise: unknown;
        terrain_remove_floating_islands: unknown;
        terrain_size_z: unknown;
        terrain_sky_ground_contrast: unknown;
        terrain_solve_random_factor: unknown;
        terrain_start_z: unknown;
        terrain_uv_relax_iterations: unknown;
        terrain_y_offset: unknown;
        readonly user_uid: unknown;
        wind_amplitude: unknown;
        wind_random_part: unknown;
    };
}